# Generated by Django 5.2.6 on 2025-10-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='addres',
            field=models.CharField(default=0),
        ),
    ]
